#ifndef ERRORCODES_H
#define ERRORCODES_H

enum {
  INVALID_ARGUMENTS = 1,
  FILE_OPEN_FAILED = 2,
  INVALID_DOCUMENT_STRUCTURE = 3,
  INVALID_PASSWORD = 4,
  FILE_NOT_ENCRYPTED = 6,
  UNKOWN_ENCRYPTION_ALGORITHM = 5
} errorcodes_e;

#endif
